### ISSUE TITLE
missing proto import error

### ISSUE THREAD

**Issue by asalzmann** [osmosis-labs/telescope#199]
I'm looking into transpiling [Stride](https://github.com/Stride-Labs/stride) protos with telescope, and running into this error
```
➜  stridejs telescope transpile
? [protoDirs] where is the proto directory? ./proto
? [outPath] where is the output directory? ./src/codegen
? [includeAminos] output amino messages? Yes
? [includeLCDClients] output LCD Clients? Yes
? [includeRPCClients] output RPC clients? Yes
/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/lookup.js:83
      throw new Error("missing proto import ".concat(imp));
            ^

Error: missing proto import gogoproto/gogo.proto
    at /usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/lookup.js:83:13
    at Array.map (<anonymous>)
    at importLookup (/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/lookup.js:79:190)
    at /usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/traverse.js:145:38
    at Array.reduce (<anonymous>)
    at traverseFields (/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/traverse.js:94:34)
    at traverseType (/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/traverse.js:289:13)
    at recursiveTraversal (/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/traverse.js:406:12)
    at Object.keys.reduce.type (/usr/local/lib/node_modules/@osmonauts/telescope/node_modules/@osmonauts/proto-parser/main/traverse.js:438:25)
    at Array.reduce (<anonymous>)
```

In the proto I'm trying to transpile, we have the following import and message
```
import "gogoproto/gogo.proto";

message ReinvestCallback {
  cosmos.base.v1beta1.Coin reinvestAmount = 1 [
    (gogoproto.nullable) = false,
    (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coin"
  ];
  string hostZoneId = 3;
}

```

I did notice there's a test in telescope that implies something with [gogoproto/gogo.proto doesn't work](https://github.com/osmosis-labs/telescope/blob/2accd236730163921f87fd93b025728ad70a26b6/packages/parser/__tests__/bad.traversal.test.ts#L23), but it's not immediately clear to me what that is.

proto directory: https://github.com/Stride-Labs/stride/tree/main/proto
possibly related issues: #108 #107

I might also be doing something basic wrong, thanks for bearing with me 😄

**Comment by pyramation** [comment]
As the error message states, `Error: missing proto import gogoproto/gogo.proto` you are simply missing the `gogoproto` protobuffers.

All good and simple fix! Simply add them to your proto directory (although I wouldn't do this in your Go repository, I'd make a new repo [like this one](https://github.com/cosmology-tech/stridejs) or we can use this and collaborate there)
