### ISSUE TITLE
packaging for vite 

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/telescope#259]
```
17:08:28.448	@redacted/app:build: [commonjs--resolver] Failed to resolve entry for package "interchain". The package may have incorrect main/module/exports specified in its package.json.
17:08:28.450	@redacted/app:build: error during build:
17:08:28.450	@redacted/app:build: Error: Failed to resolve entry for package "interchain". The package may have incorrect main/module/exports specified in its package.json.
17:08:28.450	@redacted/app:build:     at packageEntryFailure (file:///opt/home/repo/packages/dapp/node_modules/vite/dist/node/chunks/dep-557f29e6.js:34838:11)
17:08:28.451	@redacted/app:build:     at resolvePackageEntry (file:///opt/home/repo/packages/dapp/node_modules/vite/dist/node/chunks/dep-557f29e6.js:34835:5)
17:08:28.451	@redacted/app:build:     at tryNodeResolve (file:///opt/home/repo/packages/dapp/node_modules/vite/dist/node/chunks/dep-557f29e6.js:34583:20)
17:08:28.451	@redacted/app:build:     at Object.resolveId (file:///opt/home/repo/packages/dapp/node_modules/vite/dist/node/chunks/dep-557f29e6.js:34356:28)
17:08:28.451	@redacted/app:build:     at file:///opt/home/repo/packages/dapp/node_modules/rollup/dist/es/shared/rollup.js:22710:40
17:08:28.492	@redacted/app:build: ERROR: command finished with error: command (/opt/home/repo/packages/dapp) yarn run build exited (1)
17:08:28.492	command (/opt/home/repo/packages/dapp) yarn run build exited (1)
```

**Comment by pyramation** [comment]
```
cross-env BABEL_ENV=production babel src --out-dir main --delete-dir-on-start --extensions ".tsx,.ts,.js"
```

the out dir is main, not `module`!
